### ISSUE TITLE
Rails 3: Have to use Rails.env instead RAILS_ENV

### ISSUE THREAD

**Issue by tony707** [sbecker/asset_packager#14]
The helpers (with the should_merge? method) always consider the env to development, consequently the compressed files are never included in production.
The RAILS_ENV var does not exist anymore in rails 3.
You may should Rails.env instead.

**Comment by sbecker** [comment]
The helpers don't use RAILS_ENV anymore. Check out the latest version and see  http://github.com/sbecker/asset_packager/blob/master/lib/synthesis/asset_package_helper.rb
