### ISSUE TITLE
assets in subdirectories…?

### ISSUE THREAD

**Issue by dallas** [sbecker/asset_packager#5]
I'm compulsively organized—organized to a fault, some might say—and I was trying to organize my JavaScript files according to the section of the site they pertain to:

```
javascripts
javascripts/application.js
javascripts/section1/base.js
javascripts/section2/base.js
etc.
```

but they don't seem to be loading at all with the configuration I have set up:

```

---
javascripts:
- section1:
  - application
  - section1/base
```

Is there any support for nested assets on the horizon? Or does such a thing already exist and I'm a complete moron?

Any help or just a general reply would be great!

Dallas

**Comment by sbecker** [comment]
Dallas - I don't have any problems doing that - using js files in nested directories inside my packages - that is exactly how my own asset_packages.yml file is set up. I'm not exactly sure what the problem is.

Scott
